In [ ]:
print("hello")

In [ ]:
print("hello")

hello


In [8]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([2,3,4,4])
print("heloo")
print(arr1+arr2)

heloo
[3 5 7 8]


In [9]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [ ]:
print(np.ones((2,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
print(np.full((2,2),7))

[[7 7]
 [7 7]]


In [16]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
print(np.arange(1,4,1))

[1 2 3]


In [22]:
arr=np.array([1.1,2.2,3.3])
new=arr.astype(np.int32)
print(new)

[1 2 3]
